# Generated by Django 4.1.3 on 2023-12-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallerystart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='classification',
            field=models.CharField(choices=[('dashain', 'dashain'), ('tihar', 'tihar'), ('picnic', 'picnic'), ('others', 'others')], max_length=50),
        ),
    ]
