# Generated by Django 4.1.3 on 2023-12-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallerystart', '0002_alter_album_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='classification',
            field=models.CharField(max_length=50),
        ),
    ]
